// [
//     {
//       "id": "1",
//       "title": "Goku UI - GOD",
//       "size": "[H] 90cm, [W] 49cm, [D] 65cm",
//       "ratio": "1/3",
//       "producer": "Lao Niao Studio",
//       "film": "Dragon Ball",
//       "sale": "",
//       "price": "398.90",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731065040/uaf0ym0syzrz9l6qoipb.jpg",
//       "status": "Available",
//       "material": " PU, Polystone, Led"
//     },
//     {
//       "id": "2",
//       "title": "Goku Ultimate Waveget",
//       "size": "[H] 47cm, [W] 63cm, [D] 40cm",
//       "ratio": "1/4",
//       "producer": "CX Studio",
//       "film": "Dragon Ball",
//       "sale": "",
//       "price": "248.90",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731065039/veexua0kmwbgqajo3tuy.jpg",
//       "status": "Available",
//       "material": "PU, Resin, Polystone"
//     },
//     {
//       "id": "3",
//       "title": "Mabu",
//       "size": "[H] 47cm, [W] 27cm, [D] 25cm",
//       "ratio": "1/6",
//       "producer": "OverMatch Studio",
//       "film": "Dragon Ball",
//       "sale": "",
//       "price": "148.90",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731065039/nl1rukay5koa0r5qvhdh.jpg",
//       "status": "Available",
//       "material": "PU, Resin"
//     },
//     {
//       "id": "4",
//       "title": "Gogeta SSJ4 X Syn Shenron",
//       "size": "[H] 56cm, [W] 52cm, [D] 34cm",
//       "ratio": "1/6",
//       "producer": "Kylin Studio",
//       "film": "Dragon Ball",
//       "sale": "",
//       "price": "648.90",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731065040/hosgnje7vyc4qavtstax.jpg",
//       "status": "Available",
//       "material": "PU, Resin, Led"
//     },
//     {
//       "id": "5",
//       "title": "Goku SSJ3 x Dragon",
//       "size": "[H] 78cm, [W] 97cm, [D] 88cm",
//       "ratio": "1/3",
//       "producer": "Last Sleep Studio",
//       "film": "Dragon Ball",
//       "sale": "",
//       "price": "758.50",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731065038/uuicg1lqkku0guflgxci.jpg",
//       "status": "Available",
//       "material": "PU, Resin, Led"
//     },
//     {
//       "id": "6",
//       "title": "Goku x Frieza",
//       "size": "[H] 65cm, [W] 68cm, [D] 46cm",
//       "ratio": "1/4",
//       "producer": "Figure Class Studio",
//       "film": "Dragon Ball",
//       "sale": "",
//       "price": "558.50",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731065040/c86uyyfy9mh8ebr72vuc.jpg",
//       "status": "Available",
//       "material": "PU, Resin, Led"
//     },
//     {
//       "id": "7",
//       "title": "Ginyu Force",
//       "size": "[H] 46cm, [W] 60cm, [D] 52cm",
//       "ratio": "1/6",
//       "producer": "LX Studio & Wolf Studio",
//       "film": "Dragon Ball",
//       "sale": "",
//       "price": "858.50",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731065041/o39wdd2ieov2zl6ebsp4.jpg",
//       "status": "Available",
//       "material": "PU, Resin"
//     },
//     {
//       "id": "8",
//       "title": "Broly X Gogeta Blue",
//       "size": "[H] 73cm, [W] 53cm, [D] 47cm",
//       "ratio": "1/4",
//       "producer": "Yunqi Create Studio",
//       "film": "Dragon Ball",
//       "sale": "",
//       "price": "1200.30",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731065039/qypu71lr01sy4noqxc4h.jpg",
//       "status": "Available",
//       "material": "PU, Resin"
//     },
//     {
//       "id": "9",
//       "title": "Goku SSJ4S",
//       "size": "[H] 38cm, [W] 20cm, [D] 22cm",
//       "ratio": "1/6",
//       "producer": "Armyant Studio",
//       "film": "Dragon Ball",
//       "sale": "",
//       "price": "345.02",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731065039/hwkojc2jddvzbp6gutrk.jpg",
//       "status": "Available",
//       "material": "PU, Resin"
//     },
//     {
//       "id": "10",
//       "title": "Freeza 2 vs Gohan",
//       "size": "[H] 38cm, [W] 27cm, [D] 21cm",
//       "ratio": "1/8",
//       "producer": "JacksDo Studio",
//       "film": "Dragon Ball",
//       "sale": "",
//       "price": "145.02",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731065039/yta0l8hyhutefg0i5yqr.jpg",
//       "status": "Available",
//       "material": "PU, Resin"
//     },
//     {
//       "id": "11",
//       "title": "Young Gohan",
//       "size": "[H] 32cm, [W] 15cm, [D] 14cm",
//       "ratio": "1/8",
//       "producer": "LK Studio",
//       "film": "Dragon Ball",
//       "sale": "",
//       "price": "115.02",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731065041/qsqlhzhyz71trbnoyvgy.jpg",
//       "status": "Available",
//       "material": "PU, Resin"
//     },
//     {
//       "id": "12",
//       "title": "Ginyu",
//       "size": "[H] 31cm, [W] 23cm, [D] 7cm",
//       "ratio": "1/6",
//       "producer": "Break Studio",
//       "film": "Dragon Ball",
//       "sale": "",
//       "price": "99.02",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731065040/alspi4a9lxtfamp4l7jx.jpg",
//       "status": "Available",
//       "material": "PU, Resin"
//     },
//     {
//       "id": "13",
//       "title": "Broly Bust",
//       "size": "[H] 59cm, [W] 39cm, [D] 55cm",
//       "ratio": "1/4",
//       "producer": "FWX Studio",
//       "film": "Dragon Ball",
//       "sale": "",
//       "price": "209.02",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731065041/lr5mgxvt6ofj5fcfdfsn.jpg",
//       "status": "Available",
//       "material": "PU, Resin"
//     },
//     {
//       "id": "14",
//       "title": "Goku Rose Saiyan",
//       "size": "[H] 45cm, [W] 43cm, [D] 52cm",
//       "ratio": "1/4",
//       "producer": "Dream Studio",
//       "film": "Dragon Ball",
//       "sale": "",
//       "price": "500.02",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731065040/mcwf2qr6luephp7vmaq6.jpg",
//       "status": "Available",
//       "material": "PU, Resin"
//     },
//     {
//       "id": "15",
//       "title": "Gogeta Bust",
//       "size": "[H] 60cm, [W] 62cm, [D] 49cm",
//       "ratio": "1/4",
//       "producer": "SpicyHot Studio",
//       "film": "Dragon Ball",
//       "sale": "",
//       "price": "450.03",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731065039/y89pi505c2wcyacho0eq.jpg",
//       "status": "Available",
//       "material": "PU, Resin, Led"
//     },
//     {
//       "id": "16",
//       "title": "Super Sayan Goku",
//       "size": "[H] 28cm, [W] 35cm, [D] 26cm",
//       "ratio": "1/4",
//       "producer": "White Hole Studio",
//       "film": "Dragon Ball",
//       "sale": "",
//       "price": "350.03",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731065040/wrt045opyikhvbzwjhv8.jpg",
//       "status": "Available",
//       "material": "PU, Resin, Led"
//     },
//     {
//       "id": "17",
//       "title": "Jiraiya",
//       "size": "[H] 52cm, [W] 43cm, [D] 50cm",
//       "ratio": "1/4",
//       "producer": "Ventus Studio",
//       "film": "Naruto Shippuden",
//       "sale": "",
//       "price": "500.09",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731067202/rx98kasyb4kj5ni4sims.jpg",
//       "status": "Available",
//       "material": "Pu, Resin, Led"
//     },
//     {
//       "id": "18",
//       "title": "Killer B",
//       "size": "[H] 40cm, [W] 24cm, [D] 25cm",
//       "ratio": "1/4",
//       "producer": "Iron Curtain Studio",
//       "film": "Naruto Shippuden",
//       "sale": "",
//       "price": "100.09",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731067203/rbtbmaemti2ldrioltbt.jpg",
//       "status": "Available",
//       "material": "Pu, Resin"
//     },
//     {
//       "id": "19",
//       "title": "Pain",
//       "size": "[H] 72cm, [W] 55cm, [D] 54cm",
//       "ratio": "1/4",
//       "producer": "RanDian Studio",
//       "film": "Naruto Shippuden",
//       "sale": "",
//       "price": "100.09",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731067204/yfzepezg3qulf4qhnyoq.jpg",
//       "status": "Available",
//       "material": "Pu, Resin"
//     },
//     {
//       "id": "20",
//       "title": "Sasuke & Susano",
//       "size": "[H] 85cm, [W] 84cm, [D] 56cm",
//       "ratio": "1/3",
//       "producer": "Pickstar Studio",
//       "film": "Naruto Shippuden",
//       "sale": "",
//       "price": "1598.19",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731067205/wg3aqakg2ruhnz8vuuw5.jpg",
//       "status": "Available",
//       "material": "Pu, Resin, Led"
//     },
//     {
//       "id": "21",
//       "title": "Itachi x Sasuke",
//       "size": "[H] 48cm, [W] 54cm, [D] 37cm",
//       "ratio": "1/4",
//       "producer": "Surge Studio",
//       "film": "Naruto Shippuden",
//       "sale": "",
//       "price": "398.19",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731067202/mn1sig9tqwmrj4n7j9i9.jpg",
//       "status": "Available",
//       "material": "Pu, Resin, Led"
//     },
//     {
//       "id": "22",
//       "title": "Zabuza & Haku",
//       "size": "[H] 44cm, [W] 34cm, [D] 32cm",
//       "ratio": "1/6",
//       "producer": "Surge Studio",
//       "film": "Naruto Shippuden",
//       "sale": "",
//       "price": "298.19",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731067207/vzgbtxeblxxdcxfo7apr.jpg",
//       "status": "Available",
//       "material": "Pu, Resin"
//     },
//     {
//       "id": "23",
//       "title": "Namikaze Minato",
//       "size": "[H] 31cm, [W] 33cm, [D] 22cm",
//       "ratio": "1/6",
//       "producer": "VC Studio",
//       "film": "Naruto Shippuden",
//       "sale": "",
//       "price": "198.19",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731067203/ximjqatthloql1fhesl1.jpg",
//       "status": "Available",
//       "material": "Resin, Polyurethane"
//     },
//     {
//       "id": "24",
//       "title": "Terumi Mei",
//       "size": "[H] 68cm, [W] 69cm, [D] 68cm",
//       "ratio": "1/4",
//       "producer": "Konoha Studio",
//       "film": "Naruto Shippuden",
//       "sale": "",
//       "price": "1198.19",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731067205/qsmmfichhff7qji9wizq.jpg",
//       "status": "Available",
//       "material": "Resin, Polyurethane, Led"
//     },
//     {
//       "id": "25",
//       "title": "Hashirama",
//       "size": "[H] 28cm, [W] 16cm, [D] 25cm",
//       "ratio": "1/7",
//       "producer": "Rocket Studio",
//       "film": "Naruto Shippuden",
//       "sale": "",
//       "price": "98.19",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731067201/e1wxgpwswou6ds4vllwx.jpg",
//       "status": "Available",
//       "material": "Resin, PU"
//     },
//     {
//       "id": "26",
//       "title": "The Ultimate Fight Madara",
//       "size": "[H] 38cm, [W] 38cm, [D] 45cm",
//       "ratio": "1/7",
//       "producer": "Burning Wind x Ventus Studio",
//       "film": "Naruto Shippuden",
//       "sale": "",
//       "price": "398.19",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731067206/lcmfcemtqrgj39kee9x4.jpg",
//       "status": "Available",
//       "material": "Resin, PU, Led"
//     },
//     {
//       "id": "27",
//       "title": "Naruto Six Paths",
//       "size": "[H] 32cm, [W] 30cm, [D] 31cm",
//       "ratio": "1/7",
//       "producer": "Burning Wind Studio",
//       "film": "Naruto Shippuden",
//       "sale": "",
//       "price": "198.29",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731067203/yenwgmb9pr1frwmltrli.jpg",
//       "status": "Available",
//       "material": "Resin, PU"
//     },
//     {
//       "id": "28",
//       "title": "Susanoo Uchiha Itachi",
//       "size": "[H] 60cm, [W] 45cm, [D] 52cm",
//       "ratio": "1/4",
//       "producer": "Jimei Palace Studio",
//       "film": "Naruto Shippuden",
//       "sale": "",
//       "price": "1050.29",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731067206/snwklfrjnaavkctelvwj.webp",
//       "status": "Available",
//       "material": "ABS, Polyurethane, Resin"
//     },
//     {
//       "id": "29",
//       "title": "Naruto Sage",
//       "size": "[H] 70cm, [W] 65cm, [D] 75cm",
//       "ratio": "1/6",
//       "producer": "PickStar Studio",
//       "film": "Naruto Shippuden",
//       "sale": "",
//       "price": "1150.09",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731067203/kbu2tqdop0r8ilzvmpmz.jpg",
//       "status": "Available",
//       "material": "ABS, Polyurethane, Resin"
//     },
//     {
//       "id": "30",
//       "title": "Sasori",
//       "size": "[H] 44cm, [W] 32cm, [D] 35cm",
//       "ratio": "1/6",
//       "producer": "Zuoban Studio",
//       "film": "Naruto Shippuden",
//       "sale": "",
//       "price": "380.65",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731067204/mbfjtdqg2q7yig9j9xs7.jpg",
//       "status": "Available",
//       "material": "Polyurethane, Resin"
//     },
//     {
//       "id": "31",
//       "title": "Kakashi Chidori",
//       "size": "[H] 20cm, [W] 23cm, [D] 12cm",
//       "ratio": "1/7",
//       "producer": "Curtain Studio",
//       "film": "Naruto Shippuden",
//       "sale": "",
//       "price": "80.65",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731067203/o0bkl3spzd4omjgqdbsg.jpg",
//       "status": "Available",
//       "material": "Polyurethane, Resin"
//     },
//     {
//       "id": "32",
//       "title": "Kakashi & Guy",
//       "size": "[H] 62cm, [W] 44cm, [D] 44cm",
//       "ratio": "1/4",
//       "producer": "JY Studio",
//       "film": "Naruto Shippuden",
//       "sale": "",
//       "price": "380.65",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731067202/sebxbmcflipfqjlta8ii.jpg",
//       "status": "Available",
//       "material": "Polyurethane, Resin, Rubby"
//     },
//     {
//       "id": "33",
//       "title": "Zoro Purple",
//       "size": "[H] 20cm, [W] 22cm, [D] 26cm",
//       "ratio": "1/6",
//       "producer": "Warrior Studio",
//       "film": "One Piece",
//       "sale": "",
//       "price": "98.09",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731071299/Zoro_Purple.jpg",
//       "status": "Available",
//       "material": "PU, Resin"
//     },
//     {
//       "id": "34",
//       "title": "Nika Vs Kaido",
//       "size": "[H] 60cm, [W] 48cm, [D] 36cm",
//       "ratio": "1/4",
//       "producer": "Zzdd Studio",
//       "film": "One Piece",
//       "sale": "",
//       "price": "508.09",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731071302/Kaido_Luffy_Nika.jpg",
//       "status": "Available",
//       "material": "PU, Resin"
//     },
//     {
//       "id": "35",
//       "title": "Katakuri",
//       "size": "[H] 43cm, [W] 45cm, [D] 50cm",
//       "ratio": "1/6",
//       "producer": "Neijuan Studio",
//       "film": "One Piece",
//       "sale": "",
//       "price": "228.78",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731071296/Katakuri.jpg",
//       "status": "Available",
//       "material": "PU, Resin"
//     },
//     {
//       "id": "36",
//       "title": "Shank",
//       "size": "[H] 40cm, [W] 27cm, [D] 30cm",
//       "ratio": "1/6",
//       "producer": "SS Studio",
//       "film": "One Piece",
//       "sale": "",
//       "price": "254.32",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731071299/Shank.jpg",
//       "status": "Available",
//       "material": "PU, Resin"
//     },
//     {
//       "id": "37",
//       "title": "Enel",
//       "size": "[H] 61cm, [W] 45cm, [D] 38cm",
//       "ratio": "1/4",
//       "producer": "TH Studio",
//       "film": "One Piece",
//       "sale": "",
//       "price": "99.32",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731071295/Enel.jpg",
//       "status": "Available",
//       "material": "PU, Resin"
//     },
//     {
//       "id": "38",
//       "title": "Luffy Grizzly Gun",
//       "size": "[H] 42cm, [W] 50cm, [D] 38cm",
//       "ratio": "1/4",
//       "producer": "Cheng Studio",
//       "film": "One Piece",
//       "sale": "",
//       "price": "199.32",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731071297/Luffy_Grizzly_Gun.jpg",
//       "status": "Available",
//       "material": "PU, Resin, Led"
//     },
//     {
//       "id": "39",
//       "title": "Kuzan",
//       "size": "[H] 42cm, [W] 50cm, [D] 38cm",
//       "ratio": "1/4",
//       "producer": "Flower Studio",
//       "film": "One Piece",
//       "sale": "",
//       "price": "179.32",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731071296/Kuzan.webp",
//       "status": "Available",
//       "material": "PU, Resin"
//     },
//     {
//       "id": "40",
//       "title": "Ace & Blackbeard",
//       "size": "[H] 102cm, [W] 67cm, [D] 48cm",
//       "ratio": "1/3",
//       "producer": "Ferrari Studio",
//       "film": "One Piece",
//       "sale": "",
//       "price": "379.02",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731071295/Blackbeard.jpg",
//       "status": "Available",
//       "material": "PU, Resin"
//     },
//     {
//       "id": "41",
//       "title": "Kaido & Luffy Nika",
//       "size": "[H] 40cm, [W] 39cm, [D] 40cm",
//       "ratio": "1/6",
//       "producer": "LC Studio",
//       "film": "One Piece",
//       "sale": "",
//       "price": "279.82",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731071298/Nika_Vs_Kaido.jpg",
//       "status": "Available",
//       "material": "PU, Resin"
//     },
//     {
//       "id": "42",
//       "title": "Zoro x Robin",
//       "size": "[H] 40cm, [W] 39cm, [D] 40cm",
//       "ratio": "1/6",
//       "producer": "YG Studio",
//       "film": "One Piece",
//       "sale": "",
//       "price": "389.82",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731071474/Zoro_x_Robin.jpg",
//       "status": "Available",
//       "material": "PU, Resin, Led"
//     },
//     {
//       "id": "43",
//       "title": "Grizzly Gun Luffy",
//       "size": "[H] 35cm, [W] 41cm, [D] 40cm",
//       "ratio": "1/6",
//       "producer": "Reset Studio",
//       "film": "One Piece",
//       "sale": "",
//       "price": "189.82",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731071296/Grizzly_Gun_Luffy.jpg",
//       "status": "Available",
//       "material": "PU, Resin, Led"
//     },
//     {
//       "id": "44",
//       "title": "Vinsmoker Lijiu",
//       "size": "[H] 54cm, [W] 45cm, [D] 30cm",
//       "ratio": "1/4",
//       "producer": "Jimei Temple",
//       "film": "One Piece",
//       "sale": "",
//       "price": "983.66",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731071298/Vinsmoker_Lijiu.jpg",
//       "status": "Available",
//       "material": "PU, Resin, ABS"
//     },
//     {
//       "id": "45",
//       "title": "Edward Newgate",
//       "size": "[H] 70cm, [W] 58cm, [D] 41cm",
//       "ratio": "1/4",
//       "producer": "Vientiane Studio ",
//       "film": "One Piece",
//       "sale": "",
//       "price": "483.66",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731071298/Edward_Newgate.jpg",
//       "status": "Available",
//       "material": "PU, Resin"
//     },
//     {
//       "id": "46",
//       "title": "Enel Dragon",
//       "size": "[H] 35cm, [W] 33cm, [D] 28cm",
//       "ratio": "1/6",
//       "producer": "Evil Studio ",
//       "film": "One Piece",
//       "sale": "",
//       "price": "200.70",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731071295/Enel_Dragon.webp",
//       "status": "Available",
//       "material": "PU, Resin"
//     },
//     {
//       "id": "47",
//       "title": "Kaidou",
//       "size": "[H] 72cm, [W] 94cm, [D] 77cm",
//       "ratio": "1/4",
//       "producer": "Iron Curtain Studio",
//       "film": "One Piece",
//       "sale": "",
//       "price": "490.70",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731071296/Kaidou.jpg",
//       "status": "Available",
//       "material": "PU, Resin"
//     },
//     {
//       "id": "48",
//       "title": "Luffy Yonko",
//       "size": "[H] 32cm, [W] 33cm, [D] 21cm",
//       "ratio": "1/7",
//       "producer": "Warhead Studio",
//       "film": "One Piece",
//       "sale": "",
//       "price": "190.47",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731071298/Nika_Vs_Kaido.jpg",
//       "status": "Available",
//       "material": "PU, Resin"
//     },
//     {
//       "id": "49",
//       "title": "Himejima Gyoumei",
//       "size": "[H] 51cm, [W] 40cm, [D] 40cm",
//       "ratio": "1/4",
//       "producer": "Niren Studio",
//       "film": "Kimetsu",
//       "sale": "",
//       "price": "405.99",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731072210/Himejima_Gyoumei.jpg",
//       "status": "Available",
//       "material": "PU, Resin, Led"
//     },
//     {
//       "id": "50",
//       "title": "MitsuriS",
//       "size": "[H] 38cm, [W] 28cm, [D] 25cm",
//       "ratio": "1/6",
//       "producer": "QWD Studio",
//       "film": "Kimetsu",
//       "sale": "",
//       "price": "210.09",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731072213/MitsuriS.jpg",
//       "status": "Available",
//       "material": "PU, Resin"
//     },
//     {
//       "id": "51",
//       "title": "Agatsuma Zenitsu",
//       "size": "[H] 55cm, [W] 50cm, [D] 51cm",
//       "ratio": "1/4",
//       "producer": "Infinity Studio",
//       "film": "Kimetsu",
//       "sale": "",
//       "price": "910.09",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731072208/Agatsuma_Zenitsu.jpg",
//       "status": "Available",
//       "material": "Polystone, PVC, Resin, Led"
//     },
//     {
//       "id": "52",
//       "title": "Protection of Nezuko Kamado",
//       "size": "[H] 46cm, [W] 30cm, [D] 29cm",
//       "ratio": "1/4",
//       "producer": "U-King Studio",
//       "film": "Kimetsu",
//       "sale": "",
//       "price": "410.09",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731072214/Protection_of_Nezuko_Kamado.jpg",
//       "status": "Available",
//       "material": "Resin, PU, Led"
//     },
//     {
//       "id": "53",
//       "title": "Tomioka Giyuu",
//       "size": "[H] 63cm, [W] 48cm, [D] 69cm",
//       "ratio": "1/4",
//       "producer": "LX Studio",
//       "film": "Kimetsu",
//       "sale": "",
//       "price": "710.79",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731072209/Giyu_Tomioka.jpg",
//       "status": "Available",
//       "material": "Resin, PU, Led"
//     },
//     {
//       "id": "54",
//       "title": "Sound Hashira Uzui Tengen",
//       "size": "[H] 46cm, [W] 27cm, [D] 30cm",
//       "ratio": "1/6",
//       "producer": "Hero Belief Studio",
//       "film": "Kimetsu",
//       "sale": "",
//       "price": "310.79",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731072216/Sound_Hashira_Uzui_Tengen.jpg",
//       "status": "Available",
//       "material": "Resin, PU"
//     },
//     {
//       "id": "55",
//       "title": "Kamado Tanjuurou",
//       "size": "[H] 32cm, [W] 25cm, [D] 25cm",
//       "ratio": "1/6",
//       "producer": "Cheng x Jacksdo Studio",
//       "film": "Kimetsu",
//       "sale": "",
//       "price": "320.69",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731072211/Kamado_Tanjuurou.jpg",
//       "status": "Available",
//       "material": "Resin, PU"
//     },
//     {
//       "id": "56",
//       "title": "Hashibira Inosuke",
//       "size": "[H] 48cm, [W] 32cm, [D] 33cm",
//       "ratio": "1/6",
//       "producer": "Big Gecko Studio",
//       "film": "Kimetsu",
//       "sale": "",
//       "price": "445.69",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731072210/Hashibira_Inosuke.jpg",
//       "status": "Available",
//       "material": "Resin, PU"
//     },
//     {
//       "id": "57",
//       "title": "Rengoku Kyoujurou vs Akaza",
//       "size": "[H] 60cm, [W] 70cm, [D] 56cm",
//       "ratio": "1/4",
//       "producer": "LX Studio",
//       "film": "Kimetsu",
//       "sale": "",
//       "price": "545.69",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731072215/Rengoku_Kyoujurou_vs_Akaza.jpg",
//       "status": "Available",
//       "material": "Resin, PU, Led"
//     },
//     {
//       "id": "58",
//       "title": "Kokushibou",
//       "size": "[H] 36cm, [W] 21cm, [D] 23cm",
//       "ratio": "1/6",
//       "producer": "Jianke Studio",
//       "film": "Kimetsu",
//       "sale": "",
//       "price": "355.19",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731072211/Kokushibou.jpg",
//       "status": "Available",
//       "material": "Resin, PU, Led"
//     },
//     {
//       "id": "59",
//       "title": "Mitsuri FL",
//       "size": "[H] 50cm, [W] 36cm, [D] 34cm",
//       "ratio": "1/6",
//       "producer": "U King Studio",
//       "film": "Kimetsu",
//       "sale": "",
//       "price": "235.29",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731072212/Mitsuri_FL.jpg",
//       "status": "Available",
//       "material": "Resin, PU"
//     },
//     {
//       "id": "60",
//       "title": "Daki",
//       "size": "[H] 28cm, [W] 22cm, [D] 16cm",
//       "ratio": "1/6",
//       "producer": "Cheng Studio",
//       "film": "Kimetsu",
//       "sale": "",
//       "price": "185.89",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731072209/Daki.jpg",
//       "status": "Available",
//       "material": "Resin, PU"
//     },
//     {
//       "id": "61",
//       "title": "Gyutaro",
//       "size": "[H] 30cm, [W] 22cm, [D] 16cm",
//       "ratio": "1/6",
//       "producer": "Cheng Studio",
//       "film": "Kimetsu",
//       "sale": "",
//       "price": "165.89",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731072209/Gyutaro.jpg",
//       "status": "Available",
//       "material": "Resin, PU"
//     },
//     {
//       "id": "62",
//       "title": "Giyu Tomioka",
//       "size": "[H] 51cm, [W] 37cm, [D] 30cm",
//       "ratio": "1/6",
//       "producer": "JIANKE x SDS Studio",
//       "film": "Kimetsu",
//       "sale": "",
//       "price": "455.09",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731072209/Giyu_Tomioka.jpg",
//       "status": "Available",
//       "material": "Resin, PU, Led"
//     },
//     {
//       "id": "63",
//       "title": "Obanai Iguro",
//       "size": "[H] 45cm, [W] 41cm, [D] 34cm",
//       "ratio": "1/6",
//       "producer": "Magic Cube Studio",
//       "film": "Kimetsu",
//       "sale": "",
//       "price": "355.65",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731072210/Iguro_Obanai.jpg",
//       "status": "Available",
//       "material": "Resin, PU"
//     },
//     {
//       "id": "64",
//       "title": "Iguro Obanai",
//       "size": "[H] 46cm, [W] 41cm, [D] 33cm",
//       "ratio": "1/6",
//       "producer": "Wisteria Studio",
//       "film": "Kimetsu",
//       "sale": "",
//       "price": "525.65",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731072213/Obanai_Iguro.jpg",
//       "status": "Available",
//       "material": "Resin, PU"
//     },
//     {
//       "id": "65",
//       "title": "Frieza Cell Buu",
//       "size": "[H] 55cm, [W] 39cm, [D] 34cm",
//       "ratio": "1/6",
//       "producer": "Army Ant Studio",
//       "film": "Dragon Ball",
//       "sale": "40",
//       "price": "870.22",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731246919/ckn7do8ejptrbv5asfx6.webp",
//       "status": "sale",
//       "material": "Pu, Resin"
//     },
//     {
//       "id": "66",
//       "title": "Luffy Nika",
//       "size": "[H] 31cm, [W] 30cm, [D] 28cm",
//       "ratio": "1/6",
//       "producer": "Army Ant Studio",
//       "film": "One Piece",
//       "sale": "10",
//       "price": "230.22",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731246919/yrcja9uoiwc2deualkw2.jpg",
//       "status": "sale",
//       "material": "Pu, Resin"
//     },
//     {
//       "id": "67",
//       "title": "Konan",
//       "size": "[H] 31cm, [W] 30cm, [D] 28cm",
//       "ratio": "1/3",
//       "producer": "XG Studio",
//       "film": "Naruto Shippuden",
//       "sale": "10",
//       "price": "230.22",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731246919/dje7zezx7qxjqkpqaag4.jpg",
//       "status": "sale",
//       "material": "Pu, Resin"
//     },
//     {
//       "id": "68",
//       "title": "Goku UI",
//       "size": "[H] 65cm, [W] 50cm, [D] 41cm",
//       "ratio": "1/1",
//       "producer": "ZBC Studio",
//       "film": "Dragon Ball",
//       "sale": "20",
//       "price": "650.02",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731246920/gmpqkyrk0zclnfgz5hc2.jpg",
//       "status": "sale",
//       "material": "Pu, Resin"
//     },
//     {
//       "id": "69",
//       "title": "Naruto",
//       "size": "[H] 23cm, [W] 22cm, [D] 18cm",
//       "ratio": "1/6",
//       "producer": "Evil Studio",
//       "film": "Naruto Shippuden",
//       "sale": "10",
//       "price": "130.55",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731246918/hc8jassx02hz7g3tqe4m.jpg",
//       "status": "sale",
//       "material": "Pu, Resin"
//     },
//     {
//       "id": "70",
//       "title": "Ace",
//       "size": "[H] 46cm, [W] 40cm, [D] 36cm",
//       "ratio": "1/6",
//       "producer": "TH Studio",
//       "film": "One Piece",
//       "sale": "25",
//       "price": "500.02",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731246919/z2ywh2brtvmgwns9is9s.jpg",
//       "status": "sale",
//       "material": "Pu, Resin"
//     },
//     {
//       "id": "71",
//       "title": "Frieza Cell Buu",
//       "size": "[H] 55cm, [W] 39cm, [D] 35cm",
//       "ratio": "1/6",
//       "producer": "Hero Belief Studio",
//       "film": "Dragon Ball",
//       "sale": "",
//       "price": "Adjust Request",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731309053/a3efbdf8-397d-486d-9170-bd3b13315e4e.png",
//       "status": "Request",
//       "material": "Pu, Resin"
//     },
//     {
//       "id": "72",
//       "title": "Gogeta Sai",
//       "size": "[H] 50cm, [W] 30cm, [D] 28cm",
//       "ratio": "1/6",
//       "producer": "SFH Studios",
//       "film": "Dragon Ball",
//       "sale": "",
//       "price": "Adjust Reques",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731309220/5f199067-cc05-4997-a048-e3d409fd3a18.png",
//       "status": "Request",
//       "material": "Pu, Resin"
//     },
//     {
//       "id": "73",
//       "title": "Goku Blue Realm King Fist",
//       "size": "[H] 67cm, [W] 39cm, [D] 36cm",
//       "ratio": "1/4",
//       "producer": "KP Studio",
//       "film": "Dragon Ball",
//       "sale": "",
//       "price": "",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731309245/6907319b-caac-467d-9182-7aa5a8cfcfde.png",
//       "status": "Request",
//       "material": "Pu, Resin"
//     },
//     {
//       "id": "74",
//       "title": "Gohan",
//       "size": "[H] 67cm, [W] 34cm, [D] 35cm",
//       "ratio": "1/4",
//       "producer": "ZBC Studio",
//       "film": "Dragon Ball",
//       "sale": "",
//       "price": "",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731310972/958fc4e2-1901-40e0-9a23-854624e192d1.png",
//       "status": "Request",
//       "material": "Polystone, PU, Crystal Resin"
//     },
//     {
//       "id": "75",
//       "title": "Gohan",
//       "size": "[H] 67cm, [W] 34cm, [D] 35cm",
//       "ratio": "1/4",
//       "producer": "ZBC Studio",
//       "film": "Dragon Ball",
//       "sale": "",
//       "price": "",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731309273/9f26edd0-8e2e-4e83-9c47-92f536ce6deb.png",
//       "status": "Order",
//       "material": "Polystone, PU, Crystal Resin"
//     },
//     {
//       "id": "76",
//       "title": "Goku SSJ4",
//       "size": "[H] 60cm, [W] 52cm, [D] 46cm",
//       "ratio": "1/6",
//       "producer": "Kylin Studio",
//       "film": "Dragon Ball",
//       "sale": "",
//       "price": "",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731309297/94d5947d-f150-4976-a9e0-0136ead23db0.png",
//       "status": "Request",
//       "material": "Resin, PU, Polystone"
//     },
//     {
//       "id": "77",
//       "title": "Goku SSJ3 Dragon Fist",
//       "size": "[H] 55cm, [W] 36cm, [D] 40cm",
//       "ratio": "1/6",
//       "producer": "Huben Studio",
//       "film": "Dragon Ball",
//       "sale": "",
//       "price": "",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731309321/ac48d895-84f2-404f-9d08-bf2d56f8a8a6.png",
//       "status": "Request",
//       "material": "Resin, PU, Polystone"
//     },
//     {
//       "id": "78",
//       "title": "Goku SSJ3",
//       "size": "[H] 80cm, [W] 56cm, [D] 53cm",
//       "ratio": "1/2",
//       "producer": "Dayu Studio",
//       "film": "Dragon Ball",
//       "sale": "",
//       "price": "",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731309355/fadc20b6-3a5c-46b3-8fbe-496718626367.png",
//       "status": "Request",
//       "material": "Polystone, Resin"
//     },
//     {
//       "id": "79",
//       "title": "Goku Instinct",
//       "size": "[H] 220cm, [W] 120cm, [D] 120cm",
//       "ratio": "1/1",
//       "producer": "Dayu Studio",
//       "film": "Dragon Ball",
//       "sale": "",
//       "price": "385.09",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731300558/j9hw4lejqrr81lllbot1.jpg",
//       "status": "Best",
//       "material": "Polystone, Resin"
//     },
//     {
//       "id": "80",
//       "title": "Goku Dragon",
//       "size": "[H] 220cm, [W] 120cm, [D] 120cm",
//       "ratio": "1/1",
//       "producer": "Dayu Studio",
//       "film": "Dragon Ball",
//       "sale": "",
//       "price": "",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731309397/efe24682-75ad-4c6f-a0d7-0c250676e25f.png",
//       "status": "Request",
//       "material": "Resin, Polystone"
//     },
//     {
//       "id": "81",
//       "title": "Uchiha Sasuke Demon",
//       "size": "[H] 40cm, [W] 35cm, [D] 32cm",
//       "ratio": "1/4",
//       "producer": "Dream Studio",
//       "film": "Naruto Shippuden",
//       "sale": "",
//       "price": "",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731309586/34a181a6-ccf7-4699-9557-f49b8307d87f.png",
//       "status": "Request",
//       "material": "Resin, Polystone"
//     },
//     {
//       "id": "82",
//       "title": "Hatake Kakashi",
//       "size": "[H] 59cm, [W] 38cm, [D] 32cm",
//       "ratio": "1/4",
//       "producer": "CS Studio",
//       "film": "Naruto Shipuden",
//       "sale": "",
//       "price": "",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731309638/8dc97004-8d09-4283-8dbc-85e1797b3422.png",
//       "status": "Request",
//       "material": "Resin, Polystone"
//     },
//     {
//       "id": "83",
//       "title": "Hashirama Goo",
//       "size": "[H] 60cm, [W] 56cm, [D] 48cm",
//       "ratio": "1/3",
//       "producer": "Light Year Studio",
//       "film": "Naruto Shippuden",
//       "sale": "",
//       "price": "",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731309764/c9fc34a7-8539-48ab-a99c-dd566d654cb0.png",
//       "status": "Request",
//       "material": "Resin, Polystone"
//     },
//     {
//       "id": "84",
//       "title": "Cyper Punk Rengoku Kyoujurou",
//       "size": "[H] 60cm, [W] 32cm, [D] 35cm",
//       "ratio": "1/4",
//       "producer": "Black Pink Studio",
//       "film": "Kimetsu",
//       "sale": "",
//       "price": "",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731309929/fdd9958c-629a-4966-ab47-3af490ce91b0.png",
//       "status": "Request",
//       "material": "Resin, Polystone"
//     },
//     {
//       "id": "85",
//       "title": "Marco",
//       "size": "[H] 32cm, [W] 31cm, [D] 22cm",
//       "ratio": "1/6",
//       "producer": "Brain Hole Studio",
//       "film": "One Piece",
//       "sale": "",
//       "price": "",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731310013/db31a834-0c9d-4461-a389-37a5e7277b43.png",
//       "status": "Request",
//       "material": "Resin, Polystone"
//     },
//     {
//       "id": "86",
//       "title": "Samurai SS3 Goku",
//       "size": "[H] 32cm, [W] 18m, [D] 18cm",
//       "ratio": "1/6",
//       "producer": "LK Studio",
//       "film": "Dragon Ball",
//       "sale": "",
//       "price": "250.02",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731310097/527af37f-5952-42a6-941f-44ebe180d176.png",
//       "status": "2Hand",
//       "material": "Polystone, PU"
//     },
//     {
//       "id": "87",
//       "title": "Spirit Bomb Son Goku",
//       "size": "[H] 32cm, [W] 30m, [D] 63cm",
//       "ratio": "1/6",
//       "producer": "Sky Top Studio",
//       "film": "Dragon Ball",
//       "sale": "",
//       "price": "305.15",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731310121/8e9f3912-85c0-47a9-be54-50ab7361f1a6.png",
//       "status": "2Hand",
//       "material": "Resin, PU Resin, LED"
//     },
//     {
//       "id": "88",
//       "title": "Omega Shenron",
//       "size": "[H] 28cm, [W] 30m, [D] 16cm",
//       "ratio": "1/6",
//       "producer": " Ksoul x Yixin Studio",
//       "film": "Dragon Ball",
//       "sale": "",
//       "price": "215.73",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731300849/vb5axph7flogtamarfmm.jpg",
//       "status": "Best",
//       "material": "Resin, PU Resin, LED"
//     },
//     {
//       "id": "89",
//       "title": "Vegeta Blue",
//       "size": "[H] 45cm, [W] 23m, [D] 25cm",
//       "ratio": "1/6",
//       "producer": "Double S Studio",
//       "film": "Dragon Ball",
//       "sale": "",
//       "price": "332.23",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731310146/8ea5de29-32b8-4791-8e75-3e2e77aa0bef.png",
//       "status": "2Hand",
//       "material": "Resin, PU, LED"
//     },
//     {
//       "id": "90",
//       "title": "Frieza",
//       "size": "[H] 31cm, [W] 18m, [D] 25cm",
//       "ratio": "1/6",
//       "producer": "C-PR Studio",
//       "film": "Dragon Ball",
//       "sale": "",
//       "price": "130.55",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731310187/f1f160c2-834e-43eb-8c97-4bccbb9598be.png",
//       "status": "2Hand",
//       "material": "Resin, PU"
//     },
//     {
//       "id": "91",
//       "title": "Goku Rose",
//       "size": "[H] 26cm, [W] 15m, [D] 13cm",
//       "ratio": "1/8",
//       "producer": "Temple Studio",
//       "film": "Dragon Ball",
//       "sale": "",
//       "price": "100.55",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731310215/a8d31b23-d935-4aac-8e56-44de029b53f3.png",
//       "status": "2Hand",
//       "material": "Resin, PU"
//     },
//     {
//       "id": "92",
//       "title": "Lunch",
//       "size": "[H] 30cm, [W] 30m, [D] 25cm",
//       "ratio": "1/6",
//       "producer": "Blitzway & 5Pro Studio",
//       "film": "Dragon Ball",
//       "sale": "",
//       "price": "350.55",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731310242/fcc2931e-ab12-4041-aeb9-e9b2378ef012.png",
//       "status": "2Hand",
//       "material": "Resin, PU"
//     },
//     {
//       "id": "93",
//       "title": "Broly",
//       "size": "[H] 73cm, [W] 24m, [D] 30cm",
//       "ratio": "1/4",
//       "producer": "BUG Studio",
//       "film": "Dragon Ball",
//       "sale": "",
//       "price": "210.55",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731310288/8e48d354-9431-4461-9421-186fa76c17ff.png",
//       "status": "2Hand",
//       "material": "Resin, PU"
//     },
//     {
//       "id": "94",
//       "title": "Gotenks",
//       "size": "[H] 48cm, [W] 31cm, [D] 30cm",
//       "ratio": "1/6",
//       "producer": "Kylin Studio",
//       "film": "Dragon Ball",
//       "sale": "",
//       "price": "210.55",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731310315/e60f5b35-6e3e-433a-ab08-4fb7d6c2ef47.png",
//       "status": "2Hand",
//       "material": "PU, Polystone, Resin"
//     },
//     {
//       "id": "95",
//       "title": "Goku Chibi",
//       "size": "[H] 30cm, [W] 22cm, [D] 23cm",
//       "ratio": "1/6",
//       "producer": "Kylin Studio",
//       "film": "Dragon Ball",
//       "sale": "",
//       "price": "210.55",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731310358/c653f572-aa68-4ecf-b319-7363a79050ed.png",
//       "status": "2Hand",
//       "material": "PU, Polyester, Resin"
//     },
//     {
//       "id": "96",
//       "title": "Super Saiyan Goku",
//       "size": "[H] 35cm, [W] 20cm, [D] 20cm",
//       "ratio": "1/6",
//       "producer": "Break Studio",
//       "film": "Dragon Ball",
//       "sale": "",
//       "price": "110.55",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731310392/53945fe7-3e19-49ac-819a-1cb215a51097.png",
//       "status": "2Hand",
//       "material": "PU, Resin"
//     },
//     {
//       "id": "97",
//       "title": "Gohan Angry",
//       "size": "[H] 18cm, [W] 14cm, [D] 13cm",
//       "ratio": "1/6",
//       "producer": "MM Studio",
//       "film": "Dragon Ball",
//       "sale": "",
//       "price": "132.55",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731310415/a8163975-8822-49b5-b299-b5accd72b441.png",
//       "status": "2Hand",
//       "material": "PU, Resin"
//     },
//     {
//       "id": "98",
//       "title": "Vegeta & Zarbon",
//       "size": "[H] 27cm, [W] 26cm, [D] 26cm",
//       "ratio": "1/8",
//       "producer": "JacksDo Studio",
//       "film": "Dragon Ball",
//       "sale": "",
//       "price": "232.55",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731310450/75a91a33-8ca5-41d4-99cc-6b24834b2287.png",
//       "status": "2Hand",
//       "material": "PU, Resin"
//     },
//     {
//       "id": "99",
//       "title": "Six Paths of Pain",
//       "size": "[H] 39cm, [W] 26cm, [D] 19cm",
//       "ratio": "1/6",
//       "producer": "Marriott studio",
//       "film": "Naruto Shippuden",
//       "sale": "",
//       "price": "312.35",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731300988/i3bkbyyavq6frenzfe1v.jpg",
//       "status": "Best",
//       "material": "Resin, PU"
//     },
//     {
//       "id": "100",
//       "title": "Trunks",
//       "size": "[H] 38cm, [W] 25cm, [D] 33cm",
//       "ratio": "1/6",
//       "producer": "SUNYATA Studios",
//       "film": "Dragon Ball",
//       "sale": "",
//       "price": "378.90",
//       "image": "https://res.cloudinary.com/duljcbwy4/image/upload/v1731300775/pcejg3b6zymzbydom3mu.jpg",
//       "status": "Best",
//       "material": "Resin, PU"
//     }
//   ]